### ISSUE TITLE
Error when loading movie page

### ISSUE THREAD

**Issue by fanisvl** [fanisvl/ticket_alerts_web#3]
ERROR in app: Exception on /movie/12 [GET]
Traceback (most recent call last):
  File "/home/fanisvl/.local/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 639, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: target: ticket_availability.-.primary: vttablet: rpc error: code = Aborted desc = transaction 1698319458994996801: ended at 2023-10-31 07:04:24.322 UTC (exceeded timeout: 20s) (CallerID: zicohzvh0pp8t1ciyh00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fanisvl/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fanisvl/.local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fanisvl/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fanisvl/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fanisvl/repos/ticket_alerts_web/app.py", line 15, in movie_page
    movie_data = get_movie(movie_id)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/fanisvl/repos/ticket_alerts_web/database.py", line 20, in get_movie
    cursor.execute(f"SELECT * FROM upcoming_movies WHERE id={id}")
  File "/home/fanisvl/.local/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/fanisvl/.local/lib/python3.11/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fanisvl/.local/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 647, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 1105 (HY000): target: ticket_availability.-.primary: vttablet: rpc error: code = Aborted desc = transaction 1698319458994996801: ended at 2023-10-31 07:04:24.322 UTC (exceeded timeout: 20s) (CallerID: zicohzvh0pp8t1ciyh00)

**Comment by fanisvl** [comment]
Used with statement to isolate connections
